system:
  mode: debug #debug release test
  port: 8081
log:
  level: "debug"
  path: "./log_info/project_log.log"
  max_size: 10  # 日志最大 10 M
  max_age: 365   # 日志保留天数
  max_backups: 5  # 最多保留 5 个备份文件
mysql:
  dbname: mes_exp1
  host: 127.0.0.1
  max_open_conns: 100 # _mysql 最大连接数
  max_idle_conns: 20 # _mysql 最大空闲连接数
  password: zy20050608
  port: 3306
  timeout: 10s
  user: root